name: http_client
description: |
    A platform-independent HTTP client API supporting browser, console, and curl (for SOCKS proxy).
version: 1.5.2

homepage: https://github.com/isoos/http_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  buffer: ^1.2.2
  executor: '>=2.0.0 <3.0.0'
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
