name: http_client
description: |
    A platform-independent HTTP client API supporting browser, console, and curl (for SOCKS proxy).
version: 1.4.1+1

homepage: https://github.com/isoos/http_client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  buffer: ^1.0.0
  executor: '>=2.0.0 <3.0.0'
  http: ^0.12.0
  meta: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.3.0
